config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index', as: 'home'

  get 'about' => 'pages#about'

  resources :posts 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @heading = 'About us'  
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @post = Post.all
  end

  def new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    # render plain: params[:post].inspect
    @post = Post.new(post_params)
    @post.save
    redirect_to @post
  end

  private def post_params
    params.require(:post).permit(:title, :body)
  end
end
 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal">TRANSBOOK</h5>
    <nav class="my-2 my-md-0 mr-md-3">
      <span class="p-2 text-dark"><%= link_to "HOME", home_path %></span>
      <span class="p-2 text-dark"><%= link_to "NEW POST", new_post_path %></span>
<!--      <a class="p-2 text-dark" href="#">Enterprise</a>-->
<!--      <a class="p-2 text-dark" href="#">Support</a>-->
<!--      <a class="p-2 text-dark" href="#">Pricing</a>-->
    </nav>
    <a class="btn btn-outline-primary" href="#">Sign up</a>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <%= yield %>
      </div>
    </div>
  </div>

  </body>
</html>

app/views/pages/about.html.erb
 <h4><%=@heading%></h4> 

app/views/posts/index.html.erb
<h1>All POSTS</h1>
<% @post.each do |post| %>
  <h3><%=post.title %></h3>
  <p><%=post.body %></p>
<% end %>
 

app/views/posts/new.html.erb
<h2>New Posts</h2>
<%= form_for :post, url: posts_path do |f| %>
  <p>
    Name <br>
    <%= f.text_field :title, :class => 'form-control' %>
  </p>
  <p>
    Text <br>
    <%= f.text_area :body, :class => 'form-control'%>
  </p>

  <p>

    <%= f.submit :class => 'btn btn-success' %>
  </p>
<% end %>

app/views/posts/show.html.erb
<h1><%=@post.title%></h1>
<p><%=@post.body%></p>